// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/22/2025, 11:51:20 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/plugins/**/*.{js,ts,mjs}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/composables/**/*.{js,ts,mjs}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/utils/**/*.{js,ts,mjs}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/pages/index.vue","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/app.config.{js,ts,mjs}","/Users/developer_2/Desktop/micro-dashboard/apps/feature-b/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;